##
##
## Alacritty Config
## @see - https://alacritty.org/config-alacritty.html
##
## TOML v1.0.0
## @see - https://toml.io/en/v1.0.0
##

[general]
import = [
  "./dracula/dracula.toml"
]
live_config_reload = true

[window]
decorations = "None"
padding = { x = 20, y = 16 }
startup_mode = "Maximized"
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft" # -- macOS only

[font]
normal = { family = "Hack Nerd Font Propo", style = "Regular" }
size = 16

[terminal]
osc52 = "CopyPaste"

