# windows/scripts/deploy-shell.ps1 - deploy the shell + terminal + editor layer.
#
#   1. PSGallery modules (PSReadLine, PSFzf) - the oh-my-zsh plugin equivalents
#   2. $PROFILE stub -> windows/profile.ps1
#   3. Windows Terminal settings.json merge <- windows/terminal/settings.fragment.json
#   4. Neovim + IdeaVim config links
#
# Idempotent: re-running is safe. Optional-step failures become warnings.

. "$PSScriptRoot\..\lib\common.ps1"

$Root = Get-ConfigRoot
$WinDir = Join-Path $Root 'windows'

# -- 1. PSGallery modules --------------------------------------
# Installed *inside pwsh* when it exists: PowerShell 7 reads
# Documents\PowerShell\Modules, while 5.1's -Scope CurrentUser writes to
# Documents\WindowsPowerShell\Modules. Installing from the wrong host leaves the
# module invisible to the shell that actually loads the profile.
Write-Step "PowerShell modules"

$moduleScript = @'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
if (-not (Get-PackageProvider -Name NuGet -ErrorAction SilentlyContinue)) {
    Install-PackageProvider -Name NuGet -Scope CurrentUser -Force | Out-Null
}
foreach ($m in @('PSReadLine', 'PSFzf')) {
    if (Get-Module -ListAvailable -Name $m) {
        Write-Host "   $m - present, skip"
        continue
    }
    Write-Host "   installing $m"
    # -Force also suppresses the untrusted-repository prompt, so PSGallery's
    # InstallationPolicy is left as the user set it.
    Install-Module -Name $m -Scope CurrentUser -Force -AllowClobber -SkipPublisherCheck
}
'@

$pwsh = Get-Command pwsh.exe -ErrorAction SilentlyContinue
if ($pwsh) {
    $tmp = Join-Path $env:TEMP "cfg-modules-$PID.ps1"
    Write-Utf8NoBom -Path $tmp -Content $moduleScript
    & $pwsh.Source -NoProfile -ExecutionPolicy Bypass -File $tmp
    if ($LASTEXITCODE -ne 0) { Add-Warn "module install under pwsh exited $LASTEXITCODE" }
    Remove-Item $tmp -Force -ErrorAction SilentlyContinue
} else {
    Add-Warn "pwsh not found - installing modules for Windows PowerShell 5.1 only"
    Invoke-Expression $moduleScript
}

# -- 2. $PROFILE stub ------------------------------------------
# The stub is generated rather than symlinked because its content differs per
# host (5.1 needs an explicit UTF-8 read) and because Documents/ may be
# OneDrive-redirected, which symlinks there tolerate poorly.
Write-Step "PowerShell profile"

$stub = @'
# AUTO-GENERATED by ~/.config/windows/scripts/deploy-shell.ps1 - DO NOT EDIT.
# Edit ~/.config/windows/profile.ps1 instead; this stub only loads it.
$__cfgProfile = Join-Path $HOME '.config\windows\profile.ps1'
if (Test-Path $__cfgProfile) {
    if ($PSVersionTable.PSVersion.Major -ge 6) {
        . $__cfgProfile
    } else {
        # Windows PowerShell 5.1 decodes scripts as ANSI unless they carry a
        # BOM. The repo profile is UTF-8 without one, so read it explicitly or
        # every Nerd Font glyph and Korean comment arrives as mojibake.
        Invoke-Expression ([System.IO.File]::ReadAllText($__cfgProfile, [System.Text.Encoding]::UTF8))
    }
}
Remove-Variable __cfgProfile -ErrorAction SilentlyContinue
'@

$docs = [Environment]::GetFolderPath('MyDocuments')
$profileTargets = @(
    (Join-Path $docs 'PowerShell\profile.ps1'),          # PowerShell 7+
    (Join-Path $docs 'WindowsPowerShell\profile.ps1')    # Windows PowerShell 5.1
)
foreach ($target in $profileTargets) {
    if ((Test-Path $target) -and ((Get-Content $target -Raw) -notmatch 'AUTO-GENERATED by ~/\.config')) {
        $backup = "$target.bak.$([int][double]::Parse((Get-Date -UFormat %s)))"
        Copy-Item $target $backup
        Write-Ok "existing profile backed up -> $(Split-Path $backup -Leaf)"
    }
    Write-Utf8NoBom -Path $target -Content $stub
    Write-Ok "profile stub -> $target"
}

# -- 3. Windows Terminal ---------------------------------------
Write-Step "Windows Terminal settings"

$wtCandidates = @(
    (Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json'),
    (Join-Path $env:LOCALAPPDATA 'Packages\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\LocalState\settings.json'),
    (Join-Path $env:LOCALAPPDATA 'Microsoft\Windows Terminal\settings.json')
)
$wtSettings = $null
foreach ($c in $wtCandidates) { if (Test-Path $c) { $wtSettings = $c; break } }

if (-not $wtSettings) {
    Add-Warn "Windows Terminal settings.json not found - launch Terminal once, then re-run"
} else {
    $fragmentPath = Join-Path $WinDir 'terminal\settings.fragment.json'
    $fragment = Get-Content $fragmentPath -Raw -Encoding UTF8 | ConvertFrom-Json

    # Windows Terminal writes JSONC (// comments, trailing commas) but
    # ConvertFrom-Json on 5.1 rejects both. Strip line comments and trailing
    # commas before parsing; the file is rewritten from the object anyway.
    $raw = Get-Content $wtSettings -Raw -Encoding UTF8
    $stripped = [regex]::Replace($raw, '(?m)^\s*//.*$', '')
    $stripped = [regex]::Replace($stripped, ',(\s*[}\]])', '$1')
    try {
        $local = $stripped | ConvertFrom-Json
    } catch {
        Add-Warn "could not parse Windows Terminal settings.json - skipped ($($_.Exception.Message))"
        $local = $null
    }

    if ($local) {
        Copy-Item $wtSettings "$wtSettings.bak" -Force

        # schemes is an ARRAY. A blind deep merge would replace the user's whole
        # scheme list with ours, so merge by scheme name instead.
        $repoSchemes = $fragment.schemes
        $fragment.PSObject.Properties.Remove('schemes')

        $merged = Merge-JsonObject -Local $local -Repo $fragment

        $mergedNames = Get-PropertyNames -Object $merged
        $schemeList = @()
        if (($mergedNames -contains 'schemes') -and $merged.schemes) {
            $schemeList = @($merged.schemes)
        }
        foreach ($rs in $repoSchemes) {
            $schemeList = @($schemeList | Where-Object { $_.name -ne $rs.name })
            $schemeList += $rs
        }
        if ($mergedNames -contains 'schemes') {
            $merged.schemes = $schemeList
        } else {
            $merged | Add-Member -MemberType NoteProperty -Name schemes -Value $schemeList
        }

        # Make PowerShell 7 the default profile when it is present - otherwise
        # the theming lands on 5.1, which the profile explicitly degrades for.
        # Only generated profiles carry `source`; hand-written ones have
        # `commandline` instead, and reading the missing property throws under
        # StrictMode - so the presence check has to come first.
        $ps7 = $null
        if ((Get-PropertyNames -Object $merged.profiles) -contains 'list') {
            $ps7 = $merged.profiles.list | Where-Object {
                ((Get-PropertyNames -Object $_) -contains 'source') -and
                ($_.source -eq 'Windows.Terminal.PowershellCore')
            } | Select-Object -First 1
        }
        if ($ps7) {
            $merged.defaultProfile = $ps7.guid
            Write-Ok "defaultProfile -> PowerShell 7"
        } else {
            Add-Warn "PowerShell 7 profile not registered in Terminal yet - defaultProfile unchanged"
        }

        Write-Utf8NoBom -Path $wtSettings -Content ($merged | ConvertTo-Json -Depth 32)
        Write-Ok "merged into $wtSettings (backup: settings.json.bak)"
    }
}

# -- 4. Editor configs -----------------------------------------
Write-Step "editor configs"

# Neovim on Windows reads %LOCALAPPDATA%\nvim, not ~/.config/nvim. Link rather
# than exporting XDG_CONFIG_HOME, which would redirect every other XDG-aware
# tool on the machine as a side effect.
$nvimLink = Join-Path $env:LOCALAPPDATA 'nvim'
if (New-ConfigLink -Link $nvimLink -Target (Join-Path $Root 'nvim')) {
    Write-Ok "$nvimLink -> ~/.config/nvim"
}

$ideavim = Join-Path $Root '.ideavimrc'
if (Test-Path $ideavim) {
    if (New-ConfigLink -Link (Join-Path $HOME '.ideavimrc') -Target $ideavim) {
        Write-Ok "~/.ideavimrc -> ~/.config/.ideavimrc"
    }
}

Write-Step "shell deploy done"
