# windows/scripts/deploy-notifier.ps1 - wire the Windows toast into the shared
# AI notifier contract.
#
# notifier/ builds a Swift app (macOS) or a Go daemon + sender (Linux). Windows
# needs neither, because the OS already runs the notification service. The only
# thing missing is the sender the hooks look for:
#
#   claude/hooks/notify.sh, codex/hooks/notify.sh
#     SEND="${AGENT_NOTIFIER_SEND:-$HOME/.agent-notifier/bin/agent-notifier-send}"
#     ... [ -x "$SEND" ] || return 0
#
# So this drops an executable shim at exactly that path. The hooks stay
# platform-agnostic and need no Windows branch of their own - the one branch
# they did need (skipping the unix-socket wait) lives in ensure_daemon.

. "$PSScriptRoot\..\lib\common.ps1"

$Root = Get-ConfigRoot

Write-Step "AgentNotifier (Windows toast sender)"

$bash = Get-GitBashPath
if (-not $bash) {
    Add-Warn "Git Bash not found - notifier shim skipped"
    return
}

$binDir = Join-Path $HOME '.agent-notifier\bin'
if (-not (Test-Path $binDir)) { New-Item -ItemType Directory -Path $binDir -Force | Out-Null }

$toast = Join-Path $Root 'windows\notifier\toast.ps1'
if (-not (Test-Path $toast)) {
    Add-Warn "windows/notifier/toast.ps1 missing - notifier shim skipped"
    return
}

# powershell.exe, not pwsh: toast.ps1 uses the WinRT projection that PowerShell 7
# does not carry. See the header of toast.ps1.
$shim = @"
#!/usr/bin/env bash
# AUTO-GENERATED by ~/.config/windows/scripts/deploy-notifier.ps1 - DO NOT EDIT.
# Sender half of the shared AI notifier on Windows. Argument order matches the
# macOS/Linux agent-notifier-send: <title> <message> <sound> <tag>.
exec powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass \
    -File '$toast' \
    -Title "`${1:-Claude Code}" \
    -Message "`${2:-}" \
    -Sound "`${3:-Glass}" \
    -Tag "`${4:-}"
"@

# LF endings: a CRLF shebang makes bash report "bad interpreter: /usr/bin/env^M".
$shim = $shim -replace "`r`n", "`n"
$shimPath = Join-Path $binDir 'agent-notifier-send'
Write-Utf8NoBom -Path $shimPath -Content $shim

$shimPosix = ConvertTo-BashPath $shimPath
& $bash -lc "chmod +x '$shimPosix' && test -x '$shimPosix' && echo executable"
if ($LASTEXITCODE -ne 0) {
    Add-Warn "notifier shim is not executable - hooks will skip notifications"
} else {
    Write-Ok "$shimPath"
}
