%hidden MODULE_NAME="ram"
set -ogq "@catppuccin_ram_icon" " "
set -ogqF "@catppuccin_ram_color" "#{E:@thm_teal}"
set -ogq "@catppuccin_ram_text" " #{l:#(~/.config/tmux/status/ram_usage.sh)}"
source -F ~/.config/tmux/plugins/tmux/utils/status_module.conf
