#!/usr/bin/env bash
# PreToolUse hook: block access to sensitive files and lockfiles.
set -euo pipefail

input=$(cat)

if ! command -v jq &>/dev/null; then
  echo "[codex protect-files] Blocked: jq not found." >&2
  exit 2
fi

ext_patterns=(".env" ".pem" ".key" ".p12" ".pfx")
exact_patterns=("package-lock.json" "pnpm-lock.yaml" "yarn.lock" "Cargo.lock" "go.sum" "bun.lock" "bun.lockb")
segment_patterns=("credentials" "secrets")
substring_patterns=("-secret")
# Generated-artifact marker (mirrors claude/hooks/protect-files.sh): a direct edit
# is lost on the next generator run. The marker must be a DECLARATION — at line
# start, optionally behind a comment opener — or the Go-style "Code generated by
# X. DO NOT EDIT." sentence, so prose mentioning the convention does not trip it.
generated_re='^[[:space:]]*((<!--|//|/\*|#|--|;|%)[[:space:]]*)?((AUTO-?GENERATED|@generated)|code generated by .*do not edit)'
generated_scan_lines=20
# Allowlisted basenames that legitimately contain a blocked substring
# (OS secret-store helpers). Referencing or editing these is permitted.
allowlist_basenames=("mcp-secret-env.sh" "mcp-secret-set.sh")

check_file() {
  local f="$1"
  [[ -z "$f" ]] && return 1

  local base
  base="$(basename "$f")"

  # Allowlist: OS secret-store helpers legitimately contain a blocked
  # substring ('-secret'). Referencing or editing them is permitted.
  for a in "${allowlist_basenames[@]}"; do
    [[ "$base" == "$a" ]] && return 1
  done

  for p in "${ext_patterns[@]}"; do
    if [[ "$base" == *"$p" ]]; then
      echo "[codex protect-files] Blocked: '$f' matches extension pattern '$p'." >&2
      return 0
    fi
  done

  if [[ "$base" == .env.* ]]; then
    echo "[codex protect-files] Blocked: '$f' matches .env.* pattern." >&2
    return 0
  fi

  for p in "${exact_patterns[@]}"; do
    if [[ "$base" == "$p" ]]; then
      echo "[codex protect-files] Blocked: '$f' matches exact filename pattern '$p'." >&2
      return 0
    fi
  done

  for p in "${segment_patterns[@]}"; do
    if [[ "$f" == *"/$p/"* || "$f" == "$p/"* || "$base" == "$p" ]]; then
      echo "[codex protect-files] Blocked: '$f' matches path segment pattern '$p'." >&2
      return 0
    fi
  done

  for p in "${substring_patterns[@]}"; do
    if [[ "$f" == *"$p"* ]]; then
      echo "[codex protect-files] Blocked: '$f' matches substring pattern '$p'." >&2
      return 0
    fi
  done

  return 1
}

# Unlike the Claude hook, this one runs for every tool with no matcher, so it must
# never block a read. Write intent is judged ONLY by payload shape — a write carries
# the bytes it intends to write, a read does not. Deliberately not matched on
# tool_name: substring matching there blocks read-only tools whose names merely
# contain "edit"/"view"/"update" (`editor_view`, `update_view`), and an exact name
# list would go stale as Codex CLI evolves. A create with no content can only target
# a file that does not exist yet, which check_generated skips anyway.
is_write_intent() {
  printf '%s' "$input" | jq -e '
    (.tool_input // {}) | (
      has("content") or has("new_string") or has("old_string") or has("patch") or
      has("edits") or has("replacement") or has("new_str") or has("file_text") or
      has("diff")
    )
  ' >/dev/null 2>&1
}

check_generated() {
  local f="$1"
  [[ -f "$f" ]] || return 1
  local line rc=1
  shopt -s nocasematch
  while IFS= read -r line; do
    if [[ "$line" =~ $generated_re ]]; then
      echo "[codex protect-files] Blocked: '$f' declares itself generated: ${line:0:80}" >&2
      echo "[codex protect-files] Edit the source and re-run its generator." >&2
      rc=0
      break
    fi
  done < <(head -n "$generated_scan_lines" "$f" 2>/dev/null)
  shopt -u nocasematch
  return $rc
}

check_command() {
  local cmd="$1"
  [[ -z "$cmd" ]] && return 1

  # Mask allowlisted helper basenames before matching so referencing the OS
  # secret-store helpers is not blocked by the '-secret' substring.
  local scan="$cmd"
  for a in "${allowlist_basenames[@]}"; do
    scan="${scan//$a/__allowlisted__}"
  done

  local all_patterns=()
  all_patterns+=("${ext_patterns[@]}")
  all_patterns+=("${exact_patterns[@]}")
  all_patterns+=("${segment_patterns[@]}")
  all_patterns+=("${substring_patterns[@]}")
  all_patterns+=(".env.")

  for p in "${all_patterns[@]}"; do
    if [[ "$scan" == *"$p"* ]]; then
      echo "[codex protect-files] Blocked: command references sensitive pattern '$p'." >&2
      return 0
    fi
  done

  return 1
}

tool=$(printf '%s' "$input" | jq -r '.tool_name // empty' 2>/dev/null)
command_text=$(printf '%s' "$input" | jq -r '
  .tool_input.command //
  .tool_input.cmd //
  .tool_input.shell_command //
  empty
' 2>/dev/null)

case "$tool" in
  Bash|exec_command|shell_command|local_shell|command)
    if check_command "$command_text"; then
      exit 2
    fi
    ;;
esac

paths=$(printf '%s' "$input" | jq -r '
  .tool_input as $i |
  [
    $i.file_path?,
    $i.path?,
    $i.filename?,
    $i.source_path?,
    $i.destination_path?,
    $i.sourcePath?,
    $i.destinationPath?,
    ($i.files[]?.file_path?),
    ($i.files[]?.path?),
    ($i.edits[]?.file_path?),
    ($i.edits[]?.path?)
  ] | .[] | select(type == "string" and length > 0)
' 2>/dev/null)

[[ -z "$paths" ]] && exit 0

write_intent=false
if is_write_intent; then
  write_intent=true
fi

while IFS= read -r path; do
  if check_file "$path"; then
    exit 2
  fi
  if [[ "$write_intent" == true ]] && check_generated "$path"; then
    exit 2
  fi
done <<< "$paths"

exit 0
