#!/bin/bash
# claude/scripts/bootstrap.sh — deploy claude/ + ai/ shared content into ~/.claude/.
# - md files (PERSONAL, guardrails, DEVGUARD, CLAUDE) are symlinked from
#   ai/ or claude/. Tokens stay in source; the model substitutes per
#   ai/memory/feedback_ai_config_structure.md.
# - rules/ and memory/ are merged via per-file symlinks (ai/ + claude/).
# - skills/ overlay merges ai/skills/* + ai/skills/private/* + claude/skills/*.
# - MEMORY.md is auto-generated by walking memory directories.
# - settings.json, hooks/, agents/, commands/, extensions/ stay
#   Claude-only (existing behavior preserved).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT_DIR="$(cd "$REPO_DIR/.." && pwd)"
AI_DIR="$ROOT_DIR/ai"
CLAUDE_DIR="$HOME/.claude"

echo "=== claude bootstrap ==="
echo "Repo:   $REPO_DIR"
echo "Shared: $AI_DIR"
echo "Target: $CLAUDE_DIR"

# ── 0. Dependency check ──
if ! command -v jq &>/dev/null; then
    echo "ERROR: jq is required. Install: brew install jq"
    exit 1
fi
mkdir -p "$CLAUDE_DIR"

# ── 1. Symlink: top-level md files ──
echo "Linking md files..."
ln -sfn "$AI_DIR/PERSONAL.md"     "$CLAUDE_DIR/PERSONAL.md"
ln -sfn "$AI_DIR/guardrails.md"   "$CLAUDE_DIR/guardrails.md"
ln -sfn "$REPO_DIR/DEVGUARD.md" "$CLAUDE_DIR/DEVGUARD.md"
# CLAUDE.md is COPIED, not symlinked, so its @imports resolve relative to
# ~/.claude/ (where PERSONAL/guardrails symlinks live) and stay "internal".
# A symlink would resolve imports against the realpath dir (.config/claude/),
# which (a) misses ai/-tier files and (b) triggers external-include approval
# dialogs. Re-run bootstrap after editing the source CLAUDE.md.
rm -f "$CLAUDE_DIR/CLAUDE.md"   # drop any prior symlink so cp writes a real file
cp -f "$REPO_DIR/CLAUDE.md" "$CLAUDE_DIR/CLAUDE.md"
ln -sfn "$REPO_DIR/extensions/statusline.sh" "$CLAUDE_DIR/statusline.sh"

# ── 2. Symlink: hooks/, commands/, agents/ (Claude-only) ──
echo "Linking hooks/commands/agents..."
if [ -d "$CLAUDE_DIR/hooks" ] && [ ! -L "$CLAUDE_DIR/hooks" ]; then
    rm -rf "$CLAUDE_DIR/hooks"
fi
ln -sfn "$REPO_DIR/hooks" "$CLAUDE_DIR/hooks"

for dir in commands agents; do
    if [ -d "$CLAUDE_DIR/$dir" ] && [ ! -L "$CLAUDE_DIR/$dir" ]; then
        rm -rf "$CLAUDE_DIR/$dir"
    fi
    [ -d "$REPO_DIR/$dir" ] && ln -sfn "$REPO_DIR/$dir" "$CLAUDE_DIR/$dir"
done

# ── 3. rules/ merge: ai/rules/* + claude/rules/* ──
echo "Merging rules..."
[ -L "$CLAUDE_DIR/rules" ] && rm "$CLAUDE_DIR/rules"
mkdir -p "$CLAUDE_DIR/rules"
find "$CLAUDE_DIR/rules" -maxdepth 1 -type l -delete 2>/dev/null || true
for f in "$AI_DIR/rules/"*.md "$REPO_DIR/rules/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/rules/$(basename "$f")"
done

# ── 4. memory/ merge + MEMORY.md generate ──
echo "Merging memory + generating MEMORY.md..."
[ -L "$CLAUDE_DIR/memory" ] && rm "$CLAUDE_DIR/memory"
mkdir -p "$CLAUDE_DIR/memory/private"
find "$CLAUDE_DIR/memory" -maxdepth 1 -type l -delete 2>/dev/null || true
find "$CLAUDE_DIR/memory/private" -maxdepth 1 -type l -delete 2>/dev/null || true

for f in "$AI_DIR/memory/"*.md "$REPO_DIR/memory/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/memory/$(basename "$f")"
done
for f in "$AI_DIR/memory/private/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/memory/private/$(basename "$f")"
done

extract_desc() {
    awk '/^description:/ {
        sub(/^description: ?/, "")
        sub(/^"/, ""); sub(/"$/, "")
        print
        exit
    }' "$1"
}

generate_memory_index() {
    local out="$CLAUDE_DIR/MEMORY.md"
    {
        echo "<!-- AUTO-GENERATED by claude/scripts/bootstrap.sh — edit source files in ai/memory/, claude/memory/, or ai/memory/private/. -->"
        echo "# Memory Index"
        echo
        echo "## Shared"
        for f in "$AI_DIR/memory/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/$name.md) — $desc"
        done
        echo
        echo "## Claude-only"
        for f in "$REPO_DIR/memory/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/$name.md) — $desc"
        done
        echo
        echo "## Private"
        for f in "$AI_DIR/memory/private/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/private/$name.md) — $desc"
        done
    } > "$out"
}
generate_memory_index

# ── 5. skills/ overlay (ai + ai/private + claude) ──
echo "Linking skills..."
[ -L "$CLAUDE_DIR/skills" ] && rm "$CLAUDE_DIR/skills"
mkdir -p "$CLAUDE_DIR/skills"
find "$CLAUDE_DIR/skills" -maxdepth 1 -type l -delete 2>/dev/null || true

link_skill_dir() {
    local d="$1"
    [ -d "$d" ] || return 0
    [ -f "$d/SKILL.md" ] || return 0
    local target="$CLAUDE_DIR/skills/$(basename "$d")"
    # `ln -sfn DIR TARGET` descends into TARGET when TARGET is a real directory,
    # creating TARGET/$(basename DIR) instead of replacing TARGET — so a stale
    # real directory silently survives and shadows the skill with a nested link.
    # The sweep above only deletes symlinks (to preserve user-added skills), so
    # nothing else clears it. This is reachable whenever a previous deploy left
    # copies behind: on Windows that happens if MSYS=winsymlinks:nativestrict is
    # unset or Developer Mode is off, which is exactly the degraded mode
    # windows/scripts/deploy-ai.ps1 checks for.
    if [ -e "$target" ] && [ ! -L "$target" ]; then
        rm -rf "$target"
    fi
    ln -sfn "$d" "$target"
}
for d in "$AI_DIR/skills/"*/;          do link_skill_dir "$d"; done
for d in "$AI_DIR/skills/private/"*/;  do link_skill_dir "$d"; done
for d in "$REPO_DIR/skills/"*/;        do link_skill_dir "$d"; done

# ── 6. Scripts: copy executable scripts (excluding bootstrap/sync-back) ──
echo "Deploying scripts..."
mkdir -p "$CLAUDE_DIR/scripts"
for f in "$REPO_DIR/scripts/"*.sh; do
    base=$(basename "$f")
    case "$base" in
        bootstrap.sh|sync-back.sh) continue ;;
    esac
    cp "$f" "$CLAUDE_DIR/scripts/"
    chmod +x "$CLAUDE_DIR/scripts/$base"
done

# ── 7. Merge settings.json (repo keys override, local-only keys preserved) ──
echo "Merging settings.json..."
if [ -f "$CLAUDE_DIR/settings.json" ]; then
    jq -s '
      .[0] as $local | .[1] as $repo |
      $local * $repo |
      .permissions.allow = (($local.permissions.allow // []) + ($repo.permissions.allow // []) | unique) |
      .permissions.deny  = (($local.permissions.deny  // []) + ($repo.permissions.deny  // []) | unique)
    ' "$CLAUDE_DIR/settings.json" "$REPO_DIR/settings.json" \
        > "$CLAUDE_DIR/settings.json.tmp" \
        && mv "$CLAUDE_DIR/settings.json.tmp" "$CLAUDE_DIR/settings.json"
else
    cp "$REPO_DIR/settings.json" "$CLAUDE_DIR/settings.json"
fi

# ── 8. pager MCP server ──
# pager's MCP surface — msg_list, msg_roster, msg_send — is exactly what
# ai/memory/feedback_pager_poll_during_long_turns.md instructs the model to call
# mid-turn instead of waiting for hook delivery. Claude Code keeps MCP servers in
# ~/.claude.json, its own state file, which this repo does not track: so on a
# fresh machine the rule was unusable, because the tools it names simply did not
# exist. Nothing surfaced that — the rule reads fine and just never applies.
#
# Codex gets the same server from codex/config.toml.template, whose deep-merge
# does carry it. This is the Claude-side equivalent, done through the CLI rather
# than by editing ~/.claude.json by hand.
if command -v claude &>/dev/null && command -v pager &>/dev/null; then
    if claude mcp get pager &>/dev/null; then
        echo "pager MCP server already registered."
    elif claude mcp add --scope user pager -- pager mcp &>/dev/null; then
        echo "Registered pager MCP server (user scope)."
    else
        echo "WARN: could not register the pager MCP server."
    fi
fi

echo "=== claude bootstrap done ==="
