#!/bin/bash
# claude/scripts/bootstrap.sh — deploy claude/ + ai/ shared content into ~/.claude/.
# - md files (PERSONAL, guardrails, RTK, DEVGUARD, CLAUDE) are symlinked from
#   ai/ or claude/. Tokens stay in source; the model substitutes per
#   ai/memory/feedback_token_substitution.md.
# - rules/ and memory/ are merged via per-file symlinks (ai/ + claude/).
# - skills/ overlay merges ai/skills/* + ai/skills/private/* + claude/skills/*.
# - MEMORY.md is auto-generated by walking memory directories.
# - settings.json, hooks/, agents/, commands/, extensions/, notifier/ stay
#   Claude-only (existing behavior preserved).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT_DIR="$(cd "$REPO_DIR/.." && pwd)"
AI_DIR="$ROOT_DIR/ai"
CLAUDE_DIR="$HOME/.claude"

echo "=== claude bootstrap ==="
echo "Repo:   $REPO_DIR"
echo "Shared: $AI_DIR"
echo "Target: $CLAUDE_DIR"

# ── 0. Dependency check ──
if ! command -v jq &>/dev/null; then
    echo "ERROR: jq is required. Install: brew install jq"
    exit 1
fi
mkdir -p "$CLAUDE_DIR"

# ── 1. Symlink: top-level md files ──
echo "Linking md files..."
ln -sfn "$AI_DIR/PERSONAL.md"     "$CLAUDE_DIR/PERSONAL.md"
ln -sfn "$AI_DIR/guardrails.md"   "$CLAUDE_DIR/guardrails.md"
for f in CLAUDE.md RTK.md DEVGUARD.md; do
    ln -sfn "$REPO_DIR/$f" "$CLAUDE_DIR/$f"
done
ln -sfn "$REPO_DIR/extensions/statusline.sh" "$CLAUDE_DIR/statusline.sh"

# ── 2. Symlink: hooks/, commands/, agents/ (Claude-only) ──
echo "Linking hooks/commands/agents..."
if [ -d "$CLAUDE_DIR/hooks" ] && [ ! -L "$CLAUDE_DIR/hooks" ]; then
    cp "$CLAUDE_DIR/hooks/.rtk-hook.sha256" /tmp/.rtk-hook.sha256.bak 2>/dev/null || true
    rm -rf "$CLAUDE_DIR/hooks"
fi
ln -sfn "$REPO_DIR/hooks" "$CLAUDE_DIR/hooks"
cp /tmp/.rtk-hook.sha256.bak "$CLAUDE_DIR/hooks/.rtk-hook.sha256" 2>/dev/null || true

for dir in commands agents; do
    if [ -d "$CLAUDE_DIR/$dir" ] && [ ! -L "$CLAUDE_DIR/$dir" ]; then
        rm -rf "$CLAUDE_DIR/$dir"
    fi
    [ -d "$REPO_DIR/$dir" ] && ln -sfn "$REPO_DIR/$dir" "$CLAUDE_DIR/$dir"
done

# ── 3. rules/ merge: ai/rules/* + claude/rules/* ──
echo "Merging rules..."
mkdir -p "$CLAUDE_DIR/rules"
find "$CLAUDE_DIR/rules" -maxdepth 1 -type l -delete 2>/dev/null || true
for f in "$AI_DIR/rules/"*.md "$REPO_DIR/rules/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/rules/$(basename "$f")"
done

# ── 4. memory/ merge + MEMORY.md generate ──
echo "Merging memory + generating MEMORY.md..."
mkdir -p "$CLAUDE_DIR/memory/private"
find "$CLAUDE_DIR/memory" -maxdepth 1 -type l -delete 2>/dev/null || true
find "$CLAUDE_DIR/memory/private" -maxdepth 1 -type l -delete 2>/dev/null || true

for f in "$AI_DIR/memory/"*.md "$REPO_DIR/memory/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/memory/$(basename "$f")"
done
for f in "$AI_DIR/memory/private/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/memory/private/$(basename "$f")"
done

extract_desc() {
    awk '/^description:/ {
        sub(/^description: ?/, "")
        sub(/^"/, ""); sub(/"$/, "")
        print
        exit
    }' "$1"
}

generate_memory_index() {
    local out="$CLAUDE_DIR/MEMORY.md"
    {
        echo "<!-- AUTO-GENERATED by claude/scripts/bootstrap.sh — edit source files in ai/memory/, claude/memory/, or ai/memory/private/. -->"
        echo "# Memory Index"
        echo
        echo "## Shared"
        for f in "$AI_DIR/memory/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/$name.md) — $desc"
        done
        echo
        echo "## Claude-only"
        for f in "$REPO_DIR/memory/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/$name.md) — $desc"
        done
        echo
        echo "## Private"
        for f in "$AI_DIR/memory/private/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/private/$name.md) — $desc"
        done
    } > "$out"
}
generate_memory_index

# ── 5. skills/ overlay (ai + ai/private + claude) ──
echo "Linking skills..."
mkdir -p "$CLAUDE_DIR/skills"
find "$CLAUDE_DIR/skills" -maxdepth 1 -type l -delete 2>/dev/null || true

link_skill_dir() {
    local d="$1"
    [ -d "$d" ] || return
    [ -f "$d/SKILL.md" ] || return
    ln -sfn "$d" "$CLAUDE_DIR/skills/$(basename "$d")"
}
for d in "$AI_DIR/skills/"*/;          do link_skill_dir "$d"; done
for d in "$AI_DIR/skills/private/"*/;  do link_skill_dir "$d"; done
for d in "$REPO_DIR/skills/"*/;        do link_skill_dir "$d"; done

# ── 6. Scripts: copy executable scripts (excluding bootstrap/sync-back) ──
echo "Deploying scripts..."
mkdir -p "$CLAUDE_DIR/scripts"
for f in "$REPO_DIR/scripts/"*.sh; do
    base=$(basename "$f")
    case "$base" in
        bootstrap.sh|sync-back.sh) continue ;;
    esac
    cp "$f" "$CLAUDE_DIR/scripts/"
    chmod +x "$CLAUDE_DIR/scripts/$base"
done

# ── 7. Merge settings.json (repo keys override, local-only keys preserved) ──
echo "Merging settings.json..."
if [ -f "$CLAUDE_DIR/settings.json" ]; then
    jq -s '
      .[0] as $local | .[1] as $repo |
      $local * $repo |
      .permissions.allow = (($local.permissions.allow // []) + ($repo.permissions.allow // []) | unique) |
      .permissions.deny  = (($local.permissions.deny  // []) + ($repo.permissions.deny  // []) | unique)
    ' "$CLAUDE_DIR/settings.json" "$REPO_DIR/settings.json" \
        > "$CLAUDE_DIR/settings.json.tmp" \
        && mv "$CLAUDE_DIR/settings.json.tmp" "$CLAUDE_DIR/settings.json"
else
    cp "$REPO_DIR/settings.json" "$CLAUDE_DIR/settings.json"
fi

# ── 8. Build ClaudeNotifier (optional) ──
if command -v swiftc &>/dev/null; then
    echo "Building ClaudeNotifier..."
    bash "$REPO_DIR/notifier/build.sh"
fi

echo "=== claude bootstrap done ==="
