#!/bin/bash
# claude/scripts/bootstrap.sh — deploy claude/ + ai/ shared content into ~/.claude/.
# - md files (PERSONAL, guardrails, DEVGUARD, CLAUDE) are symlinked from
#   ai/ or claude/. Tokens stay in source; the model substitutes per
#   ai/memory/feedback_ai_config_structure.md.
# - rules/ and memory/ are merged via per-file symlinks (ai/ + claude/).
# - skills/ overlay merges ai/skills/* + ai/skills/private/* + claude/skills/*.
# - MEMORY.md is auto-generated by walking memory directories.
# - settings.json, hooks/, agents/, commands/, extensions/ stay
#   Claude-only (existing behavior preserved).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ROOT_DIR="$(cd "$REPO_DIR/.." && pwd)"
AI_DIR="$ROOT_DIR/ai"
CLAUDE_DIR="$HOME/.claude"

echo "=== claude bootstrap ==="
echo "Repo:   $REPO_DIR"
echo "Shared: $AI_DIR"
echo "Target: $CLAUDE_DIR"

# ── 0. Dependency check ──
if ! command -v jq &>/dev/null; then
    echo "ERROR: jq is required. Install: brew install jq"
    exit 1
fi
mkdir -p "$CLAUDE_DIR"

# ── 1. Symlink: top-level md files ──
echo "Linking md files..."
ln -sfn "$AI_DIR/PERSONAL.md"     "$CLAUDE_DIR/PERSONAL.md"
ln -sfn "$AI_DIR/guardrails.md"   "$CLAUDE_DIR/guardrails.md"
ln -sfn "$REPO_DIR/DEVGUARD.md" "$CLAUDE_DIR/DEVGUARD.md"
# CLAUDE.md is COPIED, not symlinked, so its @imports resolve relative to
# ~/.claude/ (where PERSONAL/guardrails symlinks live) and stay "internal".
# A symlink would resolve imports against the realpath dir (.config/claude/),
# which (a) misses ai/-tier files and (b) triggers external-include approval
# dialogs. Re-run bootstrap after editing the source CLAUDE.md.
rm -f "$CLAUDE_DIR/CLAUDE.md"   # drop any prior symlink so cp writes a real file
cp -f "$REPO_DIR/CLAUDE.md" "$CLAUDE_DIR/CLAUDE.md"
ln -sfn "$REPO_DIR/extensions/statusline.sh" "$CLAUDE_DIR/statusline.sh"

# ── 2. Symlink: hooks/, commands/, agents/ (Claude-only) ──
echo "Linking hooks/commands/agents..."
if [ -d "$CLAUDE_DIR/hooks" ] && [ ! -L "$CLAUDE_DIR/hooks" ]; then
    rm -rf "$CLAUDE_DIR/hooks"
fi
ln -sfn "$REPO_DIR/hooks" "$CLAUDE_DIR/hooks"

for dir in commands agents; do
    if [ -d "$CLAUDE_DIR/$dir" ] && [ ! -L "$CLAUDE_DIR/$dir" ]; then
        rm -rf "$CLAUDE_DIR/$dir"
    fi
    [ -d "$REPO_DIR/$dir" ] && ln -sfn "$REPO_DIR/$dir" "$CLAUDE_DIR/$dir"
done

# ── 3. rules/ merge: ai/rules/* + claude/rules/* ──
echo "Merging rules..."
[ -L "$CLAUDE_DIR/rules" ] && rm "$CLAUDE_DIR/rules"
mkdir -p "$CLAUDE_DIR/rules"
find "$CLAUDE_DIR/rules" -maxdepth 1 -type l -delete 2>/dev/null || true
for f in "$AI_DIR/rules/"*.md "$REPO_DIR/rules/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/rules/$(basename "$f")"
done

# ── 4. memory/ merge + MEMORY.md generate ──
echo "Merging memory + generating MEMORY.md..."
[ -L "$CLAUDE_DIR/memory" ] && rm "$CLAUDE_DIR/memory"
mkdir -p "$CLAUDE_DIR/memory/private"
find "$CLAUDE_DIR/memory" -maxdepth 1 -type l -delete 2>/dev/null || true
find "$CLAUDE_DIR/memory/private" -maxdepth 1 -type l -delete 2>/dev/null || true

for f in "$AI_DIR/memory/"*.md "$REPO_DIR/memory/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/memory/$(basename "$f")"
done
for f in "$AI_DIR/memory/private/"*.md; do
    [ -f "$f" ] || continue
    ln -sfn "$f" "$CLAUDE_DIR/memory/private/$(basename "$f")"
done

extract_desc() {
    awk '/^description:/ {
        sub(/^description: ?/, "")
        sub(/^"/, ""); sub(/"$/, "")
        print
        exit
    }' "$1"
}

generate_memory_index() {
    local out="$CLAUDE_DIR/MEMORY.md"
    {
        echo "<!-- AUTO-GENERATED by claude/scripts/bootstrap.sh — edit source files in ai/memory/, claude/memory/, or ai/memory/private/. -->"
        echo "# Memory Index"
        echo
        echo "## Shared"
        for f in "$AI_DIR/memory/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/$name.md) — $desc"
        done
        echo
        echo "## Claude-only"
        for f in "$REPO_DIR/memory/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/$name.md) — $desc"
        done
        echo
        echo "## Private"
        for f in "$AI_DIR/memory/private/"*.md; do
            [ -f "$f" ] || continue
            name=$(basename "$f" .md)
            desc=$(extract_desc "$f")
            echo "- [$name](memory/private/$name.md) — $desc"
        done
    } > "$out"
}
generate_memory_index

# ── 5. skills/ overlay (ai + ai/private + claude) ──
echo "Linking skills..."
[ -L "$CLAUDE_DIR/skills" ] && rm "$CLAUDE_DIR/skills"
mkdir -p "$CLAUDE_DIR/skills"
find "$CLAUDE_DIR/skills" -maxdepth 1 -type l -delete 2>/dev/null || true

link_skill_dir() {
    local d="$1"
    [ -d "$d" ] || return 0
    [ -f "$d/SKILL.md" ] || return 0
    local target="$CLAUDE_DIR/skills/$(basename "$d")"
    # `ln -sfn DIR TARGET` descends into TARGET when TARGET is a real directory,
    # creating TARGET/$(basename DIR) instead of replacing TARGET — so a stale
    # real directory silently survives and shadows the skill with a nested link.
    # The sweep above only deletes symlinks (to preserve user-added skills), so
    # nothing else clears it. This is reachable whenever a previous deploy left
    # copies behind: on Windows that happens if MSYS=winsymlinks:nativestrict is
    # unset or Developer Mode is off, which is exactly the degraded mode
    # windows/scripts/deploy-ai.ps1 checks for.
    # Move, never delete: a real directory here is usually a stale copy, but it
    # can equally be a user-added skill that happens to share the name, and the
    # symlink-only sweep above exists precisely to protect those. Moving is
    # recoverable and self-limiting — the next deploy finds a symlink and never
    # re-enters this branch.
    if [ -e "$target" ] && [ ! -L "$target" ]; then
        local stale="$target.stale.$(date +%s)"
        mv "$target" "$stale" || { echo "warn: cannot clear $target; skipping" >&2; return 0; }
        echo "warn: moved stale $target → $stale" >&2
    fi
    # Never fatal: one unlinkable skill must not abort the rest of the deploy.
    ln -sfn "$d" "$target" || echo "warn: cannot link $target → $d" >&2
}
for d in "$AI_DIR/skills/"*/;          do link_skill_dir "$d"; done
for d in "$AI_DIR/skills/private/"*/;  do link_skill_dir "$d"; done
for d in "$REPO_DIR/skills/"*/;        do link_skill_dir "$d"; done

# ── 6. Scripts: copy executable scripts (excluding bootstrap/sync-back) ──
echo "Deploying scripts..."
mkdir -p "$CLAUDE_DIR/scripts"
for f in "$REPO_DIR/scripts/"*.sh; do
    base=$(basename "$f")
    case "$base" in
        bootstrap.sh|sync-back.sh) continue ;;
    esac
    cp "$f" "$CLAUDE_DIR/scripts/"
    chmod +x "$CLAUDE_DIR/scripts/$base"
done

# ── 7. Merge settings.json (repo keys override, local-only keys preserved) ──
# The permission arrays cannot be unioned and cannot be replaced.
#
# A union adds but never removes, so a permission deleted from the repo lives on
# forever wherever it had already landed — dropping the blanket Bash(codex*)
# allow changed nothing on the machine that had it, and nothing said so. A plain
# replace has the opposite failure: Claude Code writes an "always allow" answer
# straight into this array, so replacing would silently revoke every approval
# given at a prompt.
#
# So the repo records what it contributed, in MANAGED. An entry that is gone
# from the repo and was last put there by the repo is a deletion and goes; an
# entry the repo never contributed is the user's and stays. A first run has no
# manifest, which reads as an empty contribution and so behaves exactly like the
# union it replaces — no machine loses a permission on the upgrade itself.
#
# deny gets the same treatment rather than staying union-only. A stale deny is
# harmless where a stale allow is not, but the rule that is easy to reason about
# is "the repo says what is allowed and what is denied", and one array following
# a different rule than the other is how the next surprise gets built.
#
# The one case it cannot see: an entry the repo dropped that the user then
# re-approved at a prompt. That reads as a deletion and is removed again. It
# fails toward fewer permissions, and re-approving is one keystroke.
#
# Both jq writes below go through tr: jq on Windows opens stdout in text mode
# and turns every newline into CRLF. See claude/scripts/sync-back.sh, where the
# same conversion lands on a tracked file and does real damage. A raw CR cannot
# appear inside jq JSON output, so dropping all of them is safe, and on macOS
# and Linux there are none to drop.
MANAGED="$CLAUDE_DIR/.settings-repo-managed.json"
MERGED=0
echo "Merging settings.json..."
if [ -f "$CLAUDE_DIR/settings.json" ]; then
    # A missing, truncated or malformed manifest is reset rather than handed to
    # jq, which would error on it, abort this script, and — the orchestrator
    # calls it unguarded under its own set -e — take the codex deploy, the
    # notifier build and both sanity checks down with it. Reset reads as an
    # empty contribution, which is exactly the union this replaces: a pending
    # deletion waits one run and no permission is lost.
    jq -e 'type == "object" and has("allow") and has("deny")' "$MANAGED" >/dev/null 2>&1 \
        || echo '{"allow":[],"deny":[]}' > "$MANAGED"
    # ask gets the same rule as allow and deny. It is another array Claude Code
    # appends to from a prompt, so leaving it to `*` alone would let a repo that
    # ever gains an `ask` key replace the user's accumulated entries wholesale -
    # the same accident as a unioned allow, mirrored. Only touched when one side
    # actually has the key, so settings.json does not grow an empty `ask: []`.
    if jq -s '
      .[0] as $local | .[1] as $repo | .[2] as $was |
      def resolve($k):
        (($local.permissions[$k] // []) - ($was[$k] // []))
        + ($repo.permissions[$k] // []) | unique;
      $local * $repo |
      .permissions.allow = resolve("allow") |
      .permissions.deny  = resolve("deny") |
      if ($local.permissions.ask // $repo.permissions.ask)
      then .permissions.ask = resolve("ask") else . end
    ' "$CLAUDE_DIR/settings.json" "$REPO_DIR/settings.json" "$MANAGED" \
        | tr -d '\r' > "$CLAUDE_DIR/settings.json.tmp"
    then
        mv "$CLAUDE_DIR/settings.json.tmp" "$CLAUDE_DIR/settings.json"
        MERGED=1
    else
        rm -f "$CLAUDE_DIR/settings.json.tmp"
        echo "warn: settings.json merge failed; left as-is, manifest not advanced" >&2
    fi
else
    cp "$REPO_DIR/settings.json" "$CLAUDE_DIR/settings.json"
    MERGED=1
fi
# Only after a merge that actually landed. Writing it unconditionally was worse
# than writing it early: the manifest would describe the repo's current state
# while settings.json still held the old one, so the entry the repo had just
# dropped was no longer recorded as the repo's - and the next run read it as the
# user's and kept it. That loses the deletion permanently, not for one run.
# Through a temp file because a redirect that dies midway leaves a half-written
# manifest for the next run to cope with.
if [ "$MERGED" -eq 1 ]; then
    jq '{allow: (.permissions.allow // []), deny: (.permissions.deny // []), ask: (.permissions.ask // [])}' \
        "$REPO_DIR/settings.json" | tr -d '\r' > "$MANAGED.tmp" \
        && mv "$MANAGED.tmp" "$MANAGED"
fi

# ── 8. pager MCP server ──
# pager's MCP surface — msg_list, msg_roster, msg_send — is exactly what
# ai/memory/feedback_pager_poll_during_long_turns.md instructs the model to call
# mid-turn instead of waiting for hook delivery. Claude Code keeps MCP servers in
# ~/.claude.json, its own state file, which this repo does not track: so on a
# fresh machine the rule was unusable, because the tools it names simply did not
# exist. Nothing surfaced that — the rule reads fine and just never applies.
#
# Codex gets the same server from codex/config.toml.template, whose deep-merge
# does carry it. This is the Claude-side equivalent, done through the CLI rather
# than by editing ~/.claude.json by hand.
if command -v claude &>/dev/null && command -v pager &>/dev/null; then
    if claude mcp get pager &>/dev/null; then
        echo "pager MCP server already registered."
    elif claude mcp add --scope user pager -- pager mcp &>/dev/null; then
        echo "Registered pager MCP server (user scope)."
    else
        echo "WARN: could not register the pager MCP server."
    fi
fi

echo "=== claude bootstrap done ==="
