#!/bin/bash
# codex/scripts/bootstrap.sh
# - Build ~/.codex/AGENTS.md from ai/AGENTS.manifest with sed token expand.
# - Overlay ai/skills/* + ai/skills/private/* + codex/skills/* into ~/.agents/skills/.
# - Merge codex/config.toml.template with the user's existing [mcp_servers.*] blocks.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
AI_DIR="$ROOT_DIR/ai"
CODEX_DIR="$ROOT_DIR/codex"

mkdir -p "$HOME/.codex"
mkdir -p "$HOME/.agents/skills"

echo "=== codex bootstrap ==="

# ── 1. Token expand (codex side) ──
expand_tokens_codex() {
    sed \
        -e "s|{{TOOL_HOME}}|$HOME/.codex|g" \
        -e "s|{{TOOL_NAME}}|Codex CLI|g" \
        -e "s|{{TOOL_NAME_LC}}|codex|g" \
        -e "s|{{INSTRUCTIONS_FILE}}|AGENTS.md|g" \
        -e "s|{{CONFIG_FILE}}|config.toml|g" \
        -e "s|{{PLAN_DIR}}|.codex/plans|g" \
        -e "s|{{STATE_DIR}}|.codex/state|g"
}

# ── 2. Strip frontmatter (the leading `---`...`---` block, if present) ──
strip_frontmatter() {
    awk 'BEGIN{c=0} /^---$/{c++; next} c>=2 || c==0'
}

# ── 3. Build AGENTS.md ──
MANIFEST="$AI_DIR/AGENTS.manifest"
TARGET="$HOME/.codex/AGENTS.md"
TMP="$TARGET.tmp"

[ -f "$MANIFEST" ] || { echo "ERROR: $MANIFEST missing"; exit 1; }

{
    echo "<!-- AUTO-GENERATED by codex/scripts/bootstrap.sh from ai/AGENTS.manifest. Edit source files in ai/, not this file. -->"
    echo
    while IFS= read -r line; do
        case "$line" in
            ''|'#'*) continue ;;
        esac
        src="$AI_DIR/$line"
        if [ ! -f "$src" ]; then
            # Private memory may be gitignored; warn but skip
            echo "<!-- WARN: manifest references missing $line — skipped -->"
            continue
        fi
        echo "<!-- $line -->"
        strip_frontmatter < "$src" | expand_tokens_codex
        echo
    done < "$MANIFEST"
} > "$TMP"
mv "$TMP" "$TARGET"
SIZE=$(wc -c < "$TARGET" | tr -d ' ')
echo "Built ~/.codex/AGENTS.md ($SIZE B)"

# ── 4. config.toml — yq deep merge: template keys enforced, user keys preserved ──
TARGET_CFG="$HOME/.codex/config.toml"
TEMPLATE="$CODEX_DIR/config.toml.template"

if [ ! -f "$TARGET_CFG" ]; then
    cp "$TEMPLATE" "$TARGET_CFG"
    echo "Wrote ~/.codex/config.toml from template (first deploy)"
else
    if ! command -v yq &>/dev/null; then
        echo "ERROR: yq required for config.toml deep merge (brew install yq)"
        exit 1
    fi
    yq -p toml -o toml '. *= load("'"$TEMPLATE"'")' "$TARGET_CFG" > "$TARGET_CFG.tmp" \
        && mv "$TARGET_CFG.tmp" "$TARGET_CFG"
    echo "Merged config.toml (template keys enforced; user keys preserved)"
fi

# ── 5. Skills overlay → ~/.agents/skills/ ──
# Preserve user-added (non-symlink) entries; remove only old symlinks.
find "$HOME/.agents/skills" -maxdepth 1 -mindepth 1 -type l -delete 2>/dev/null || true

link_skill_dir() {
    local d="$1"
    [ -d "$d" ] || return 0
    [ -f "$d/SKILL.md" ] || return 0
    ln -sfn "$d" "$HOME/.agents/skills/$(basename "$d")"
}
for d in "$AI_DIR/skills/"*/; do link_skill_dir "$d"; done
for d in "$AI_DIR/skills/private/"*/; do link_skill_dir "$d"; done
for d in "$CODEX_DIR/skills/"*/; do link_skill_dir "$d"; done

echo "Skills overlay deployed → ~/.agents/skills/"
echo "=== codex bootstrap done ==="
