#!/bin/bash
# codex/scripts/bootstrap.sh
# - Build ~/.codex/AGENTS.md from ai/AGENTS.manifest with sed token expand.
# - Append Codex-only instruction addendum from codex/DEVGUARD.md.
# - Overlay ai/skills/* + ai/skills/private/* + codex/skills/* into ~/.agents/skills/.
# - Merge codex/config.toml.template with user-managed local config blocks.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
AI_DIR="$ROOT_DIR/ai"
CODEX_DIR="$ROOT_DIR/codex"

mkdir -p "$HOME/.codex"
mkdir -p "$HOME/.agents/skills"

echo "=== codex bootstrap ==="

# ── 1. Token expand (codex side) ──
expand_tokens_codex() {
    sed \
        -e "s|{{TOOL_HOME}}|$HOME/.codex|g" \
        -e "s|{{TOOL_NAME}}|Codex CLI|g" \
        -e "s|{{TOOL_NAME_LC}}|codex|g" \
        -e "s|{{INSTRUCTIONS_FILE}}|AGENTS.md|g" \
        -e "s|{{CONFIG_FILE}}|config.toml|g" \
        -e "s|{{PLAN_DIR}}|.agents/plans|g" \
        -e "s|{{STATE_DIR}}|.agents/state|g"
}

# ── 2. Strip frontmatter (the leading `---`...`---` block, if present) ──
strip_frontmatter() {
    awk 'BEGIN{c=0} /^---$/{c++; next} c>=2 || c==0'
}

# ── 3. Build AGENTS.md ──
MANIFEST="$AI_DIR/AGENTS.manifest"
TARGET="$HOME/.codex/AGENTS.md"
TMP="$TARGET.tmp"

[ -f "$MANIFEST" ] || { echo "ERROR: $MANIFEST missing"; exit 1; }

{
    echo "<!-- AUTO-GENERATED by codex/scripts/bootstrap.sh from ai/AGENTS.manifest. Edit source files in ai/, not this file. -->"
    echo
    while IFS= read -r line; do
        case "$line" in
            ''|'#'*) continue ;;
        esac
        src="$AI_DIR/$line"
        if [ ! -f "$src" ]; then
            # Private memory may be gitignored; warn but skip
            echo "<!-- WARN: manifest references missing $line — skipped -->"
            continue
        fi
        echo "<!-- $line -->"
        strip_frontmatter < "$src" | expand_tokens_codex
        echo
    done < "$MANIFEST"
    if [ -f "$CODEX_DIR/DEVGUARD.md" ]; then
        echo "<!-- codex/DEVGUARD.md -->"
        strip_frontmatter < "$CODEX_DIR/DEVGUARD.md" | expand_tokens_codex
        echo
    fi
} > "$TMP"
mv "$TMP" "$TARGET"
SIZE=$(wc -c < "$TARGET" | tr -d ' ')
echo "Built ~/.codex/AGENTS.md ($SIZE B)"

# ── 4. config.toml — yq deep merge: template keys enforced, user keys preserved ──
TARGET_CFG="$HOME/.codex/config.toml"
TEMPLATE="$CODEX_DIR/config.toml.template"

# Expand machine-specific placeholders (tmux socket uid) into a temp copy so the
# committed template carries no hardcoded uid and stays portable across machines.
TEMPLATE_EXPANDED="$(mktemp)"
trap 'rm -f "$TEMPLATE_EXPANDED"' EXIT
sed "s|tmux-__UID__|tmux-$(id -u)|g" "$TEMPLATE" > "$TEMPLATE_EXPANDED"
TEMPLATE="$TEMPLATE_EXPANDED"

# pager is an external binary this repo installs only on Windows, so declaring
# [mcp_servers.pager] unconditionally makes every Codex session on a fresh
# macOS/Linux machine try to spawn a missing command. Mirror the Claude surface,
# which registers it only when the binary is present. Stripping the template
# alone is not enough — the deep merge keeps target-only keys, so an entry a
# previous deploy wrote would survive; DEL_KEYS removes it from the result too.
DEL_KEYS='.UserPromptSubmit, .PreToolUse, .PostToolUse, .PreCompact, .SessionStart, .Stop, .PermissionRequest'
if ! command -v pager &>/dev/null; then
    if command -v yq &>/dev/null; then
        yq -i -p toml -o toml 'del(.mcp_servers.pager)' "$TEMPLATE_EXPANDED"
        DEL_KEYS="$DEL_KEYS, .mcp_servers.pager"
        echo "Skipped [mcp_servers.pager] (pager not installed)"
    else
        echo "warn: pager absent and yq missing — [mcp_servers.pager] left declared" >&2
    fi
fi

if [ ! -f "$TARGET_CFG" ]; then
    cp "$TEMPLATE" "$TARGET_CFG"
    echo "Wrote ~/.codex/config.toml from template (first deploy)"
else
    if ! command -v yq &>/dev/null; then
        echo "ERROR: yq required for config.toml deep merge (brew install yq)"
        exit 1
    fi
    if yq eval-all -p toml -o toml \
        "select(fileIndex == 0) * select(fileIndex == 1) | del($DEL_KEYS)" \
        "$TARGET_CFG" "$TEMPLATE" > "$TARGET_CFG.tmp"; then
        mv "$TARGET_CFG.tmp" "$TARGET_CFG"
    else
        rm -f "$TARGET_CFG.tmp"
        echo "ERROR: failed to merge config.toml with template" >&2
        exit 1
    fi
    echo "Merged config.toml (template keys enforced; user keys preserved)"
fi

# ── 5. Skills overlay → ~/.agents/skills/ ──
# Preserve user-added (non-symlink) entries; remove only old symlinks.
find "$HOME/.agents/skills" -maxdepth 1 -mindepth 1 -type l -delete 2>/dev/null || true

link_skill_dir() {
    local d="$1"
    [ -d "$d" ] || return 0
    [ -f "$d/SKILL.md" ] || return 0
    local target="$HOME/.agents/skills/$(basename "$d")"
    # See claude/scripts/bootstrap.sh: `ln -sfn DIR TARGET` descends into a real
    # TARGET directory rather than replacing it, leaving a nested link that
    # shadows the skill. The symlink-only sweep above cannot clear that — and it
    # exists to protect user-added skills, so clear it by moving, never deleting.
    if [ -e "$target" ] && [ ! -L "$target" ]; then
        local stale="$target.stale.$(date +%s)"
        mv "$target" "$stale" || { echo "warn: cannot clear $target; skipping" >&2; return 0; }
        echo "warn: moved stale $target → $stale" >&2
    fi
    ln -sfn "$d" "$target" || echo "warn: cannot link $target → $d" >&2
}
for d in "$AI_DIR/skills/"*/; do link_skill_dir "$d"; done
for d in "$AI_DIR/skills/private/"*/; do link_skill_dir "$d"; done
for d in "$CODEX_DIR/skills/"*/; do link_skill_dir "$d"; done

echo "Skills overlay deployed → ~/.agents/skills/"

# ── 6. Built-in system skills opt-out ──
# Codex installs its bundled skills under ~/.codex/skills/.system when the
# marker is missing or stale. Keeping the current marker while removing the
# skill directories suppresses bundled skills without affecting user skills.
if [ "${CODEX_DISABLE_SYSTEM_SKILLS:-1}" = "1" ]; then
    SYSTEM_SKILLS_DIR="$HOME/.codex/skills/.system"
    SYSTEM_SKILLS_MARKER="$SYSTEM_SKILLS_DIR/.codex-system-skills.marker"
    if [ ! -f "$SYSTEM_SKILLS_MARKER" ] && command -v codex &>/dev/null; then
        codex debug prompt-input "bootstrap-system-skill-marker" >/dev/null 2>&1 || true
    fi
    if [ -f "$SYSTEM_SKILLS_MARKER" ]; then
        find "$SYSTEM_SKILLS_DIR" -mindepth 1 -maxdepth 1 ! -name ".codex-system-skills.marker" -exec rm -rf {} +
        echo "Built-in system skills disabled → ~/.codex/skills/.system/"
    else
        echo "Built-in system skills disable skipped (marker not available)"
    fi
fi

# ── 7. Remove an imported Claude hook layer ──
# Codex imports Claude Code's hooks on first run: it writes ~/.codex/hooks.json
# from ~/.claude/settings.json and copies ~/.claude/hooks/ to ~/.codex/hooks/.
# That is wrong for this repo in three ways:
#   - it duplicates the hooks config.toml already defines, and Codex itself then
#     warns "loading hooks from both ... prefer a single representation"
#   - the imported set is CLAUDE's: stop-handler.sh, compact-restore.sh and
#     log-instructions.sh have no codex counterpart, and codex's own stop-gate.sh
#     is not among them
#   - the commands point at the copies under ~/.codex/hooks/, so editing the
#     real sources in ~/.config/codex/hooks/ silently stops taking effect
# config.toml is this repo's single representation, so the import is removed.
# Backed up rather than deleted, since it is not ours to throw away outright.
for imported in "$HOME/.codex/hooks.json" "$HOME/.codex/hooks"; do
    if [ -e "$imported" ]; then
        mv "$imported" "$imported.imported.bak.$(date +%s)"
        echo "Removed imported Claude hook layer: $(basename "$imported") (backup kept)"
    fi
done

echo "=== codex bootstrap done ==="
